In [2]:
import numpy as np

In [7]:
#1-converting list into array 
lst = [1,2,3,4]
arr = np.array(lst)
print(arr)
type(arr)
type(lst)

[1 2 3 4]


list

In [9]:
#we can also add dimension while converting
arr1 = np.array(lst , ndmin = 2)
print(arr1)

[[1 2 3 4]]


In [10]:
#2-Arrange function
arr = np.arange(1,10,2) # start stop separate
print(arr)

[1 3 5 7 9]


In [17]:
#3- Multidimensional array
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]]


In [19]:
#4- Size function - finds how many elements are present in an array
print(arr.size) # this gives us total size
print(np.size(arr,0)) #this gives size of rows since 0 indicate rows
print(np.size(arr,1)) # this gives size of column

12
4
3


In [20]:
#5- dtype - gives the data type of array
print(arr.dtype)

int32


In [21]:
#6- ndim - gives dimenstion of array
print(arr.ndim)

2


In [22]:
#7- Zero function - It creates zero matrix for the given dimension and type
arr = np.zeros(shape = (3,4), dtype = int)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [4]:
#8- Ones function - It is similar to zeros function, it creates 1's matrix inplace of zero
arr = np.ones(shape = (5,5), dtype = int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
#9- Eye function - identity matrix 
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [10]:
#10- Empty function - returns an empty array of given shape and size
arr = np.empty(shape = (5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#11- Random functions
np.random.rand(3,4) # 1st type

array([[0.28861412, 0.50943094, 0.54683666, 0.34667918],
       [0.58295777, 0.82489793, 0.3700464 , 0.24818404],
       [0.31772093, 0.66264238, 0.28981229, 0.37053104]])

In [17]:
#2nd type - it returns random integers value within the range
np.random.randint(low = 0, high = 10, size = 10)

array([6, 0, 3, 2, 0, 3, 1, 7, 7, 8])

In [18]:
#3rd type - it creates random values as per the standard normal distribution
np.random.randn(20)

array([ 1.43799744, -0.93164428, -1.90003076, -2.24222538,  0.70562474,
       -0.5770049 ,  0.10589995, -0.60755821,  1.17246552, -1.02794216,
        0.50278032, -2.44523149, -1.6519626 ,  2.05237381, -0.97607661,
       -0.96678357,  0.69394352,  0.17916338, -0.15138824, -0.70810097])

In [22]:
#12- Reshape function- only reshapes if the matrix size is same 
arr = np.random.randint(1,10,(3,4))
print(arr.shape)
print(arr)
arr = arr.reshape(4,3)
print(arr.shape)
print(arr)

(3, 4)
[[5 3 7 9]
 [5 8 3 4]
 [5 8 9 4]]
(4, 3)
[[5 3 7]
 [9 5 8]
 [3 4 5]
 [8 9 4]]


In [25]:
#13- Linspace function-similar to rearange , in place of step it takes the how many number should be generated
np.linspace(1,10,7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [29]:
#14- Flatten function - it returns the 2d array in single d array of same element
arr = np.array([[1,2,3],
              [4,5,6]])
print(arr.shape)
print(arr)
arr = arr.flatten()
print(arr.shape)
print(arr)

(2, 3)
[[1 2 3]
 [4 5 6]]
(6,)
[1 2 3 4 5 6]


In [31]:
#15- logspace function
print(np.logspace(2,4,5))

[  100.           316.22776602  1000.          3162.27766017
 10000.        ]


In [38]:
#16- copy function - when we use = to then the id of arrays are same so inorder to overcome this we use copy function
arr = np.random.randint(1,20,5)
print("Initial array is :", arr , "and its id is :", id(arr))
arr1 = arr
print("Copied array using equals to is :", arr1, "and its id is :", id(arr1))

#Now let us see the difference using copy function
arr1 = np.copy(arr)
print("Copied array using copy function is :", arr1, "and its id is :", id(arr1))


Initial array is : [ 2  6 13 10 14] and its id is : 2013856692720
Copied array using equals to is : [ 2  6 13 10 14] and its id is : 2013856692720
Copied array using copy function is : [ 2  6 13 10 14] and its id is : 2013856692432


In [41]:
#17- array min , max and sum fuction
#For the whole array 
arr = np.random.randint(1,20,(3,5))
print(arr)
print("Max element is: ", arr.max())
print("Min element is: ", arr.min())
print("Sum of elements is: ", arr.sum())

#For particular row - use axis = 1 and similary for column use axis = 0
print("Max element is: ", arr.max(axis = 1))
print("Min element is: ", arr.min(axis = 1))
print("Sum of elements is: ", arr.sum(axis = 1))


[[17  2  4 14  4]
 [ 6  4  9 11 12]
 [ 2 18  5  2  7]]
Max element is:  18
Min element is:  2
Sum of elements is:  117
Max element is:  [17 12 18]
Min element is:  [2 4 2]
Sum of elements is:  [41 42 34]


In [49]:
#18 - seed function- used to generate pseudorandom numbers (i.e the numbers which is not completely random, we can determine it)
#after we define seed number, then the number generated will be same throughtout, it won't change as it was changing while creating normal random numbers
np.random.seed(6)
np.random.randint(1,10,(3,5))

array([[4, 5, 1, 2, 2],
       [5, 2, 9, 3, 5],
       [3, 6, 7, 3, 6]])

In [55]:
#19 - sorting function
np.random.seed(6)
arr = np.random.randint(1,10,(3,5))
print(arr)
#normal sort
print("Sorted array is: ")
arr = np.sort(arr)
print(arr)
#sort column wise
print("Sorted columnwise: ")
arr = np.sort(arr, axis = 0)
print(arr)
print("Sorted rowwise: ")
arr = np.sort(arr, axis = 1)
print(arr)

[[4 5 1 2 2]
 [5 2 9 3 5]
 [3 6 7 3 6]]
Sorted array is: 
[[1 2 2 4 5]
 [2 3 5 5 9]
 [3 3 6 6 7]]
Sorted columnwise: 
[[1 2 2 4 5]
 [2 3 5 5 7]
 [3 3 6 6 9]]
Sorted rowwise: 
[[1 2 2 4 5]
 [2 3 5 5 7]
 [3 3 6 6 9]]


In [59]:
#20- Mathematical operations
np.random.seed(3)
arr = np.random.randint(1,10,(3,5))
print(arr)
#Addition
print(arr + 1)
#Subtract
print(arr - 1)
#Multiply
print(arr * 1)
#Divide
print(arr / 2)
#floor division
print(arr //2)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
[[10  5 10 10  2]
 [ 7  5  7  9  8]
 [ 2  6  9 10  3]]
[[8 3 8 8 0]
 [5 3 5 7 6]
 [0 4 7 8 1]]
[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
[[4.5 2.  4.5 4.5 0.5]
 [3.  2.  3.  4.  3.5]
 [0.5 2.5 4.  4.5 1. ]]
[[4 2 4 4 0]
 [3 2 3 4 3]
 [0 2 4 4 1]]


In [61]:
#Matrix multiplication
arr1 = np.random.randint(1,5,(2,2))
arr2 = np.random.randint(2,7,(2,2))
print(arr1)
print(arr2)
#Multiplication is done using dot operator
print(arr1.dot(arr2))

[[2 1]
 [3 2]]
[[4 2]
 [5 2]]
[[13  6]
 [22 10]]


In [62]:
#power operation
arr = np.random.randint(1,5,(2,2))
print(arr)
print(arr **2)

[[4 2]
 [4 4]]
[[16  4]
 [16 16]]


In [64]:
#21 - percentile function
arr = np.random.randint(1,10,5)
print(arr)

#sorting the array
arr = np.sort(arr)
print(arr)

#finding the percentile
print(np.percentile(arr, 50))

[6 5 8 7 1]
[1 5 6 7 8]
6.0


In [65]:
#22 - mean, varience and standard deviation
np.random.seed(3)
arr = np.random.randint(1,10,10)
print(arr)
#Mean
print(arr.mean())
#varience
print(arr.var())
#standard deviation
print(arr.std())

[9 4 9 9 1 6 4 6 8 7]
6.3
6.410000000000001
2.5317977802344327


In [69]:
#23- Filtering an numpy array
arr = np.arange(1,10)
print(arr)

#checking if the value in the array is greater than 5 or not
print(arr > 5)

#printing the number which are greater than 5
print(arr[arr > 5])

#we can also change the value in another value
arr[arr > 5] = 11
print(arr)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
[ 1  2  3  4  5 11 11 11 11]


In [71]:
#24- Transpose of an array
arr = np.random.randint(1,10,(3,2))
print(arr)
print("Transpose of an array is: ", arr.T)

[[3 3]
 [2 4]
 [6 9]]
Transpose of an array is:  [[3 2 6]
 [3 4 9]]


In [ ]:
#25- where function - is used to replace specific place where the condition statisfy
arr = np.random.randint(1,100, 10)
print(arr)
#replacing even numbers with 100
print(np.where(arr%2 == 0, 100, arr))

In [73]:
#26- Turning pics into numpy array
<img src='flower.jpg'>

SyntaxError: invalid syntax (1276950957.py, line 2)

In [74]:
from matplotlib.image import imread

In [75]:
img = imread('flower.jpg')
img.shape

(2736, 3648, 3)